const RECALL_STALE = "STALE";
const RECALL_NO_SNAPSHOT = "NO_SNAPSHOT";
const RECALL_NO_STORE = "NO_STORE";
const RECALL_AGENT_BUSY = "AGENT_BUSY";
const RECALL_ROLLBACK_FAILED = "ROLLBACK_FAILED";
const RECALL_UNKNOWN_PATH = "UNKNOWN_PATH";
const RECALL_BAD_TYPE = "BAD_TYPE";
const RECALL_EMPTY_PATCH = "EMPTY_PATCH";
const RECALL_SETTINGS_UNAVAILABLE = "SETTINGS_UNAVAILABLE";
const RECALL_SETTINGS_WRITE_FAILED = "SETTINGS_WRITE_FAILED";
const RECALL_BODY_TOO_LARGE = "BODY_TOO_LARGE";
const RECALL_ERROR = "ERROR";
const RECALL_NO_ROOT = "NO_ROOT";
const RECALL_NO_SESSION = "NO_SESSION";
const RECALL_PARTIAL_DELETE = "PARTIAL_DELETE";
const RECALL_UNKNOWN_OP = "UNKNOWN_OP";
const RECALL_UNKNOWN_ENDPOINT = "UNKNOWN_ENDPOINT";
const RECALL_INDEX_CORRUPT = "INDEX_CORRUPT";
const ALL_CODES = Object.freeze([
  RECALL_STALE,
  RECALL_NO_SNAPSHOT,
  RECALL_NO_STORE,
  RECALL_AGENT_BUSY,
  RECALL_ROLLBACK_FAILED,
  RECALL_UNKNOWN_PATH,
  RECALL_BAD_TYPE,
  RECALL_EMPTY_PATCH,
  RECALL_SETTINGS_UNAVAILABLE,
  RECALL_SETTINGS_WRITE_FAILED,
  RECALL_BODY_TOO_LARGE,
  RECALL_ERROR,
  RECALL_NO_ROOT,
  RECALL_NO_SESSION,
  RECALL_PARTIAL_DELETE,
  RECALL_UNKNOWN_OP,
  RECALL_UNKNOWN_ENDPOINT,
  RECALL_INDEX_CORRUPT
]);
export {
  ALL_CODES,
  RECALL_AGENT_BUSY,
  RECALL_BAD_TYPE,
  RECALL_BODY_TOO_LARGE,
  RECALL_EMPTY_PATCH,
  RECALL_ERROR,
  RECALL_INDEX_CORRUPT,
  RECALL_NO_ROOT,
  RECALL_NO_SESSION,
  RECALL_NO_SNAPSHOT,
  RECALL_NO_STORE,
  RECALL_PARTIAL_DELETE,
  RECALL_ROLLBACK_FAILED,
  RECALL_SETTINGS_UNAVAILABLE,
  RECALL_SETTINGS_WRITE_FAILED,
  RECALL_STALE,
  RECALL_UNKNOWN_ENDPOINT,
  RECALL_UNKNOWN_OP,
  RECALL_UNKNOWN_PATH
};
